config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about' #名前付きルート

  #get 'post_images/new'
  #get 'post_images/index'
  #get 'post_images/show'
  #上記3つをまとめて書いた形
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] #resourceと単数形になっています。単数刑にすると/idがURLに含まれなくなります。
    resources :post_comments, only: [:create, :destroy]
    #コメントは投稿画面に対してコメントされます。このため、post_commentsはpost_imagesに結びつきます。このような親子関係を「ネストする」といいます。
  end


  #get 'users/show'
  #get 'users/edit'
  resources :users, only: [:show, :edit, :update] #上記2つをまとめて書いた形

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_images, dependent: :destroy  #UserモデルにPostImageモデルを関連付ける。Userモデルに対してPostImageモデルが1:Nになるように関連付ける
  #has_manyは直訳すると「たくさん持っている」なので、1:Nの「1」側に当たるモデルに、has_manyを記載する必要がある


  has_many :post_comments, dependent: :destroy  #UserモデルとPostCommentモデルの関連付け。User側 1:N PostComment側


  has_one_attached :profile_image #profile_imageという名でActiveStorageでプロフィール画像を保存できるように設定した。


  has_many :favorites, dependent: :destroy



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed  #画像サイズの変更。
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    #@post_images = @user.post_images  #特定のユーザー(@user)に関連付けられた投稿全て(.post_images)を取得し@post_imagesに渡すという処理を行うことができる。
                                      #結果的に、全体の投稿ではなく、個人が投稿した全てを表示できます。
    @post_images = @user.post_images.page(params[:page]) #1ページ分の決められた数のデータだけを新しい順に取得するように変更。
  end

  def edit
    #user = User.find(params[:id])  #下記3つの記述によりログインしているユーザー以外が編集ができなくなる。
    #unless user.id == current_user.id
      #redirect_to post_images_path
    #end

    #is_matching_login_user  #下記にメソッドとしてまとめたため、上記の[before_action]を使用することができるようになった

    @user = User.find(params[:id])
  end

  def update
    #user = User.find(params[:id])  #下記3つの記述によりログインしているユーザー以外がアップデートできなくなる
    #unless user.id == current_user.id
      #redirect_to post_images_path
    #end

    #is_matching_login_user   #下記にメソッドとしてまとめたため、上記の[before_action]を使用することができるようになった

    @user = User.find(params[:id]) #ユーザーの取得
    @user.update(user_params) #ユーザーのアップデート
    redirect_to user_path(current_user.id)
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def is_matching_login_user  #この記載により上記の同じコードを置き換えることができる。
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with model: @user do |f| %>

  <label for = "inputName">Name</label>
  <%= f.text_field :name, autofocus: :true, id:"inputName", placeholder:"名前" %>

  <label for = "inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "/image/*" %>

  <%= f.submit "変更を保存" %>

<% end %>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div>
  <h3>
    <%= @user.name %>
  </h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>


<!-- ユーザーの投稿一覧 -->
<!-- @post_images.each do |post_image| %>
<div>
   link_to post_image_path(post_image.id) do %>
     image_tag post_image.get_image %>
   end %>

  <p>
    投稿ユーザー画像 :  image_tag post_image.user.get_profile_image(100,100) %>
  </p>
  <p>
    ショップ名 :  post_image.shop_name %>
  </p>
  <p>
    説明 :  post_image.caption %>
  </p>
  <p>
    ユーザーネーム :  post_image.user.name %>
  </p>
  <p>
     link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %> <!--コメント件数を表示する記述-->
  <!--/p-->

<!--/div-->
<!-- end -->


<!-- 上記を部分テンプレートでまとめて下記に記述する -->

<%= render 'post_images/list', post_images: @post_images %>
<!--違うフォルダーに部分テンプレートがあるため、フォルダ名を指定する必要がある-->