config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about' #名前付きルート

  #get 'post_images/new'
  #get 'post_images/index'
  #get 'post_images/show'
  #上記3つをまとめて書いた形
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] #resourceと単数形になっています。単数刑にすると/idがURLに含まれなくなります。
    resources :post_comments, only: [:create, :destroy]
    #コメントは投稿画面に対してコメントされます。このため、post_commentsはpost_imagesに結びつきます。このような親子関係を「ネストする」といいます。
  end


  #get 'users/show'
  #get 'users/edit'
  resources :users, only: [:show, :edit, :update] #上記2つをまとめて書いた形

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image


  belongs_to :user  #has_manyとは逆に、1:Nの「N」側に当たるモデルに、belongs_toを記載する必要がある。
  #belongs_toとは直訳すると「～に属する」という意味。


  has_many :post_comments, dependent: :destroy #PostImageモデルにPostCommentモデルとの関連付け。 PostImageモデル 1:N PostCommentモデル。


  has_many :favorites, dependent: :destroy


#バリデーションの設定
  validates :shop_name, presence: true #shop_nameが存在しているかを確認するバリデーション
  validates :image, presence: true #imageが存在しているかを確認するバリデーション


  #下記は画像が投稿されていない場合にエラーが出るため、回避するための記述
  #def get_image
   # if image.attached?
    #  image
    #else
      #'no_image.jpg'
    #end
  #end

  #画像が存在しない場合に表示する画像をActiveStorageに格納するための記述。
  #今回は画像のサイズ変更をRailsで行うので、上記の記述を修正して記述します。
  def get_image  #画像が設定されない場合はapp/assets/imagesに格納されているno_image.jpgという画像をデフォルト画像としてActiveStageに格納し、格納した画像を表示するということが記載されている。
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image
  end

  def favorited_by?(user) #このメソッドで引数で渡されたユーザーidがFavoritesテーブル内に存在(exists?)するかどうかを調べます。存在していればtrue,存在していなければfalseを返すようにしています。
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create  #投稿データの保存
    @post_image = PostImage.new(post_image_params) #投稿するデータをPostImageモデルに日モズクデータとして保存する準備。フォームに入力されたデータが@post_imageに格納されることになっている
    @post_image.user_id = current_user.id #「@post_image.user_id」、つまりこの当行のuser_idとしてcurrent_user.idの値を代入するという意味になる。
                                          #「current_user」は、コードを記述するだけで、ログイン中のユーザー情報を取得できる便利な記述。deviseをインストールしていたら使用可能
    if @post_image.save
      redirect_to post_images_path
    else                                  #if式を用いて、対象のカラム(ここではimageとshop_name)にデータが保存された場合はsaveメソッド(@post_image.save)が
                                          #trueになり、今まで通りredirect_toによりリダイレクト処理が走り、バリデーションなどにより保存できなかった場合はsaveメソッドがfaleの処理を行う
      render :new
    end
  end


  def index
    #@post_images = PostImage.all
    @post_images = PostImage.page(params[:page]) #1ページ分の決められた数のデータだけを新しい順に取得するように変更。
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new #コメントを投稿するためのインスタンス変数を定義する。
  end

  def destroy
    post_image = PostImage.find(params[:id])  #データを1件取得
    post_image.destroy   #データを削除
    redirect_to post_images_path
  end


  private  #投稿データのストロングパラメータ

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %> <!--コントローラから渡された@post_images変数内から1つすつ取り出してpost_image変数へ格納します。-->
    <!-- インスタンス変数(@post_images)で記述されていましたが、部分テンプレートファイル内でインスタンス変数を利用すると、-->
    <!--controller側でインスタンス変数の名前や挙動を変更したとき、部分テンプレート側も変更しなければなりません。これでは再利用しにくいテンプレートになる-->
    <!--部分テンプレートが呼び出されたときに、Viewから渡される変数が使えるように変更します。この変数には、ローカル変数(post_images)を使用。-->

  <div class="card w-50 mx-auto mt-4 shadow-lg">

      <%= link_to post_image_path(post_image.id) do %> <!--詳細ページへのリンク-->
      <!--link_toでは、doからendの間が、aタグで囲まれた状態になる。結果、image_tagは、aタグに囲まれたimgタグになります-->
        <%= image_tag post_image.get_image, class:"card-img-top"; %> <!--imge_tagを使いpost_imageにActiveStorageで設定したimageを表示しています。-->
                                          <!--「post_image.get_image」の部分はPostImageモデル内に記述したメソッドを呼び出しています -->
      <% end %>

    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <!--投稿ユーザー画像 image_tag 'sample-author1.jpg' -->
          <!--上記の記述は仮で書いていたため修正する-->
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
        <p class="card-title">
          <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
          <strong>
            <i class="far fa-flag"></i>
            <span><%= post_image.shop_name %></span> <!--post_image変数のshop_nameカラムの表示 -->
          </strong>
          <% end %>
        </p>
        <p class="card-text">
          説明 : <%= post_image.caption %> <!--post_image変数のcaptionカラムの表示 -->
        </p>
        <span>
          <i class="fas fa-user"></i> By <%= post_image.user.name %> <!--post_image変数のuser_idに関連付けられているuserモデルのnameカラムの表示 -->
        </span>
        <span>
          <%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %> <!--コメント件数を表示する記述-->
        </span>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= paginate post_images %>  <!--ページネーション機能で、1つのページに表示できる数を制限する-->
</div>

app/views/post_images/index.html.erb
<!-- @post_images.each do |post_image| %> <!--コントローラから渡された@post_images変数内から1つすつ取り出してpost_image変数へ格納します。-->
  <!--div -->

    <!-- link_to post_image_path(post_image.id) do %> <!--詳細ページへのリンク-->
    <!--link_toでは、doからendの間が、aタグで囲まれた状態になる。結果、image_tagは、aタグに囲まれたimgタグになります-->
    <!-- image_tag post_image.get_image %> <!--imge_tagを使いpost_imageにActiveStorageで設定したimageを表示しています。-->
                                          <!--「post_image.get_image」の部分はPostImageモデル内に記述したメソッドを呼び出しています -->
    <!-- end-->

    <!--p-->
      <!--投稿ユーザー画像 image_tag 'sample-author1.jpg' -->
      <!--上記の記述は仮で書いていたため修正する-->
    <!--  投稿ユーザー画像 :  image_tag post_image.user.get_profile_image(100,100) %>
    </p>
    <p>
      ショップ名 :  post_image.shop_name %> <!--post_image変数のshop_nameカラムの表示 -->
    <!--/p
    <p>
      説明 :  post_image.caption %> <!--post_image変数のcaptionカラムの表示 -->
    <!--/p
    <p>
      ユーザーネーム :  post_image.user.name %> <!--post_image変数のuser_idに関連付けられているuserモデルのnameカラムの表示 -->
    <!--/p
    <p>
       link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %> <!--コメント件数を表示する記述-->
    <!--/p
  </div>
 end %>

 <!-- 上記を部分テンプレートでまとめて下記に記述する -->

<%= render 'list', post_images: @post_images %>
<!-- render '部分テンプレートファイルの指定', ローカル変数: 渡す値 と上記が開設できる-->

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>


      <div class="form-body p-4">
        <!--エラーメッセージの記述-->
        <% if @post_image.errors.any? %>  <!--any?と組み合わせることで、エラーが発生しているかどうか判定できる-->
        <ul class="alert alert-danger" role="alert">
          <h6 class="alert-heading">
            <%= @post_image.errors.count %>件のエラーが発生しました
          </h6>
          <% @post_image.errors.full_messages.each do |message| %>  <!--full_messageと組み合わせることでエラーの内容を出力できる-->
                                                              <!--エラー文は配列で保存されているため、eachを使用する-->
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
        <% end %>


        <%= form_with model: @post_image do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>  <!--画像アップロードフィールドの実装-->
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントはここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= image_tag @post_image.get_image %>

  <p>
    ショップ名 : <%= @post_image.shop_name %>
  </p>
  <p>
    説明 : <%= @post_image.caption %>
  </p>
  <p>
    投稿ユーザー画像 : <%= image_tag @post_image.user.get_profile_image(100,100) %>
  </p>
  <p>
    ユーザーネーム : <%= @post_image.user.name %>
  </p>
  <p>
    投稿日時 : <%= @post_image.created_at.strftime('%Y/%m/%d') %>  <!--(%Y/%m/%d)は年/月/日のフォーマットへ変更します-->
  </p>

  <% if @post_image.user == current_user %>  <!--もし、投稿者==現在ログインしているユーザーだったら-->
    <%= link_to "削除", post_image_path(@post_image), method: :delete %> <!--削除ボタン-->
  <% end %>


    <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% end %>

</div>


<div>
  <p>
    コメント件数 : <%= @post_image.post_comments.count %>
  </p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p>
      <%= image_tag post_comment.user.get_profile_image(100,100) %>
    </p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>


    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>

  <% end %>
</div>


<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
  <!--コメントは、post_imageに結びついたpost_commentであるため、インスタンス変数を2つ用意する必要がある-->
  <!--また、post_commentをcreateするためのリクエストはルーティングもネスト（親子関係）しているため上記２つの情報が必要になります-->
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>