config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about' #名前付きルート

  #get 'post_images/new'
  #get 'post_images/index'
  #get 'post_images/show'
  #上記3つをまとめて書いた形
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] #resourceと単数形になっています。単数刑にすると/idがURLに含まれなくなります。
    resources :post_comments, only: [:create, :destroy]
    #コメントは投稿画面に対してコメントされます。このため、post_commentsはpost_imagesに結びつきます。このような親子関係を「ネストする」といいます。
  end


  #get 'users/show'
  #get 'users/edit'
  resources :users, only: [:show, :edit, :update] #上記2つをまとめて書いた形

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name = "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/1bb6d6e90e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navber-expand-lg navbar-light">
         <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %> <!--ログイン済みであればif user_signed_in?からelse間のコードが表示される -->
        <li class="nav-item">
          <%= link_to '投稿フォーム', new_post_image_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'マイページ', user_path(current_user.id) %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
            </ul>
          </div>
          </div>
        </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

        <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>